version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: backend_container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/testdb

volumes:
  mongo_data: {}
